const pagesWithLabels = Object.freeze({
  AddPost: {
    Main: "AddPost.",
    "4MegMessage": "AddPost.4MegMessage",
    AddPostInstructions: "AddPost.AddPostInstructions",
    AddPostPageTitle: "AddPost.AddPostPageTitle",
    AddPostPhotoTitle: "AddPost.AddPostPhotoTitle",
    BadCaptcha: "AddPost.BadCaptcha",
    FailureMessage: "AddPost.FailureMessage",
    FileNameMessage: "AddPost.FileNameMessage",
    FinishButton: "AddPost.FinishButton",
    Legend: "AddPost.Legend",
    PostCategoryPickerLabel: "AddPost.PostCategoryPickerLabel",
    PostCategoryRequired: "AddPost.PostCategoryRequired",
    PostDescriptionLabel: "AddPost.PostDescriptionLabel",
    PostDescriptionRequired: "AddPost.PostDescriptionRequired",
    PostPhotoErrorMessage: "AddPost.PostPhotoErrorMessage",
    PostPhotoTitle: "AddPost.PostPhotoTitle",
    PostPriceLabel: "AddPost.PostPriceLabel",
    PostPriceRequired: "AddPost.PostPriceRequired",
    PostTitleLabel: "AddPost.PostTitleLabel",
    PostTitleRequired: "AddPost.PostTitleRequired",
    PriceNumber: "AddPost.PriceNumber",
    SuccessMessage: "AddPost.SuccessMessage",
  },
  Category: {
    Main: "Category.",
    CategoryDescription: "Category.CategoryDescription",
    CategoryEnglishDescriptionLabel: "Category.CategoryEnglishDescriptionLabel",
    CategoryEnglishLabel: "Category.CategoryEnglishLabel",
    CategoryInstructions2: "Category.CategoryInstructions2",
    CategoryJapaneseDescriptionLabel:
      "Category.CategoryJapaneseDescriptionLabel",
    CategoryJapaneseLabel: "Category.CategoryJapaneseLabel",
    CategoryPickerLabel: "Category.CategoryPickerLabel",
    CategoryTitle: "Category.CategoryTitle",
    ErrorMessage: "Category.ErrorMessage",
    FinishButton: "Category.FinishButton",
    Instructions: "Category.Instructions",
    SuccessMessage: "Category.SuccessMessage",
    Title: "Category.Title",
  },
  ChangePass: {
    Main: "ChangePass.",
    ChangePasswordPushButton: "ChangePass.ChangePasswordPushButton",
    ConfirmNewPasswordLabel: "ChangePass.ConfirmNewPasswordLabel",
    ConfirmNewPasswordRequired: "ChangePass.ConfirmNewPasswordRequired",
    CurrentPasswordLabel: "ChangePass.CurrentPasswordLabel",
    CurrentPasswordRequired: "ChangePass.CurrentPasswordRequired",
    Instructions: "ChangePass.Instructions",
    Instructions2: {
      Main: "ChangePass.Instructions2.",
      Part1: "ChangePass.Instructions2.Part1",
      Part2: "ChangePass.Instructions2.Part2",
    },
    Legend: "ChangePass.Legend",
    NewPasswordCompare: "ChangePass.NewPasswordCompare",
    NewPasswordLabel: "ChangePass.NewPasswordLabel",
    NewPasswordRequired: "ChangePass.NewPasswordRequired",
    Success: "ChangePass.Success",
    Title: "ChangePass.Title",
  },
  ContactFailure: {
    Main: "ContactFailure.",
    Message: "ContactFailure.Message",
    Title: "ContactFailure.Title",
  },
  ContactSuccess: {
    Main: "ContactSuccess.",
    Success: "ContactSuccess.Success",
    Title: "ContactSuccess.Title",
  },
  ContactUs: {
    Main: "ContactUs.",
    ContactBodyLabel: "ContactUs.ContactBodyLabel",
    ContactBodyRequired: "ContactUs.ContactBodyRequired",
    ContactCaptchaRequired: "ContactUs.ContactCaptchaRequired",
    ContactEmailLabel: "ContactUs.ContactEmailLabel",
    ContactEmailRequired: "ContactUs.ContactEmailRequired",
    ContactUsInstructions: "ContactUs.ContactUsInstructions",
    ContactUsTitle: "ContactUs.ContactUsTitle",
    FinishButton: "ContactUs.FinishButton",
    IsEmail: "ContactUs.IsEmail",
    Legend: "ContactUs.Legend",
    Subject: "ContactUs.Subject",
  },
  ContactUser: {
    Main: "ContactUser.",
    ContactBodyLabel: "ContactUser.ContactBodyLabel",
    ContactBodyRequired: "ContactUser.ContactBodyRequired",
    ContactCaptchaRequired: "ContactUser.ContactCaptchaRequired",
    ContactEmailRequired: "ContactUser.ContactEmailRequired",
    ContactUserEmailLabel: "ContactUser.ContactUserEmailLabel",
    ContactUserInstructions: "ContactUser.ContactUserInstructions",
    ContactUserTitle: "ContactUser.ContactUserTitle",
    FinishButton: "ContactUser.FinishButton",
    IsEmail: "ContactUser.IsEmail",
    Legend: "ContactUser.Legend",
  },
  ContactUsFailure: {
    Main: "ContactUsFailure.",
    Message: "ContactUsFailure.Message",
    Title: "ContactUsFailure.Title",
  },
  ContactUsSuccess: {
    Main: "ContactUsSuccess.",
    Message: "ContactUsSuccess.Message",
    Title: "ContactUsSuccess.Title",
  },
  EditPost: {
    Main: "EditPost.",
    EditPostInstructions: "EditPost.EditPostInstructions",
    EditPostPageTitle: "EditPost.EditPostPageTitle",
    FinishButton: "EditPost.FinishButton",
    Legend: "EditPost.Legend",
    PostDescriptionLabel: "EditPost.PostDescriptionLabel",
    PostDescriptionRequired: "EditPost.PostDescriptionRequired",
    PostPriceLabel: "EditPost.PostPriceLabel",
    PostPriceRequired: "EditPost.PostPriceRequired",
    PostStatusLabel: "EditPost.PostStatusLabel",
    PostTitleLabel: "EditPost.PostTitleLabel",
    PostTitleRequired: "EditPost.PostTitleRequired",
    SuccessMessage: "EditPost.SuccessMessage",
  },
  Email: {
    Main: "Email.",
    BodyString1: "Email.BodyString1",
    BodyString2: "Email.BodyString2",
    BodyString3: "Email.BodyString3",
    BodyString4: "Email.BodyString4",
    BodyString5: "Email.BodyString5",
    BodyString6: "Email.BodyString6",
    BodyString7: "Email.BodyString7",
    BodyString8: "Email.BodyString8",
    Subject: "Email.Subject",
  },
  ExpiryEmail: {
    Main: "ExpiryEmail.",
    Line1: "ExpiryEmail.Line1",
    Line2: "ExpiryEmail.Line2",
    Line3: "ExpiryEmail.Line3",
    Line4: "ExpiryEmail.Line4",
    Subject: "ExpiryEmail.Subject",
  },
  ForgotPass: {
    Main: "ForgotPass.",
    ForgotPasswordLabel: "ForgotPass.ForgotPasswordLabel",
    ForgotPasswordPushButton: "ForgotPass.ForgotPasswordPushButton",
    Instructions: "ForgotPass.Instructions",
    Legend: "ForgotPass.Legend",
    Line1: "ForgotPass.Line1",
    Line2: "ForgotPass.Line2",
    Line3: "ForgotPass.Line3",
    Subject: "ForgotPass.Subject",
    Title: "ForgotPass.Title",
  },
  ForgotPasswordEmailSent: {
    Main: "ForgotPasswordEmailSent.",
    Message: "ForgotPasswordEmailSent.Message",
    Title: "ForgotPasswordEmailSent.Title",
  },
  LabelText: {
    Main: "LabelText.",
    CancelButton: "LabelText.CancelButton",
    ddlLabelID: "LabelText.ddlLabelID",
    EnglishRequiredMessage: "LabelText.EnglishRequiredMessage",
    FinishButton: "LabelText.FinishButton",
    Instructions: "LabelText.Instructions",
    LabelEntryFailure: "LabelText.LabelEntryFailure",
    LabelEntrySuccess: "LabelText.LabelEntrySuccess",
    LabelTextErrorMessage: "LabelText.LabelTextErrorMessage",
    Legend: "LabelText.Legend",
    Title: "LabelText.Title",
    txtEnglish: "LabelText.txtEnglish",
    txtJapanese: "LabelText.txtJapanese",
  },
  Login: {
    Main: "Login.",
    btnLogin: "Login.btnLogin",
    ForgotPassword: "Login.ForgotPassword",
    Legend: "Login.Legend",
    LoginFailMsg: "Login.LoginFailMsg",
    LoginPageInst: "Login.LoginPageInst",
    LoginPageTitle: "Login.LoginPageTitle",
    PassRequired: "Login.PassRequired",
    PasswordLabel: "Login.PasswordLabel",
    RegisterHyperLink: "Login.RegisterHyperLink",
    RegisterInstructions: "Login.RegisterInstructions",
    RememberMe: "Login.RememberMe",
    UserNameLabel: "Login.UserNameLabel",
    UserRequired: "Login.UserRequired",
  },
  Main: {
    Main: "Main.",
    Instructions: "Main.Instructions",
  },
  Master: {
    Main: "Master.",
    btnAdd: "Master.btnAdd",
    btnAdmin: "Master.btnAdmin",
    btnCategory: "Master.btnCategory",
    btnContact: "Master.btnContact",
    btnHome: "Master.btnHome",
    btnLabel: "Master.btnLabel",
    btnMember: "Master.btnMember",
    btnMy: "Master.btnMy",
    btnNumbers: "Master.btnNumbers",
    btnPassword: "Master.btnPassword",
    btnProfile: "Master.btnProfile",
    btnSearch: "Master.btnSearch",
    btnTest: "Master.btnTest",
    btnTest1: "Master.btnTest1",
    lblDisplayLanguage: "Master.lblDisplayLanguage",
    lblFooter: "Master.lblFooter",
    lblLogin: "Master.lblLogin",
    lblLogout: "Master.lblLogout",
    lblTitle: "Master.lblTitle",
    lblWelcome: "Master.lblWelcome",
    lnkSwitchDesktop: "Master.lnkSwitchDesktop",
    lnkSwitchMobile: "Master.lnkSwitchMobile",
  },
  PostList: {
    Main: "PostList.",
    btnNext: "PostList.btnNext",
    btnPrev: "PostList.btnPrev",
    cheapToExp: "PostList.cheapToExp",
    EmptyList: "PostList.EmptyList",
    expToCheap: "PostList.expToCheap",
    ItemsPerPageLabel: "PostList.ItemsPerPageLabel",
    newToOld: "PostList.newToOld",
    oldToNew: "PostList.oldToNew",
    SortOptionsLabel: "PostList.SortOptionsLabel",
  },
  PostStatus: {
    Main: "PostStatus.",
    Active: "PostStatus.Active",
    Expired: "PostStatus.Expired",
    Sold: "PostStatus.Sold",
  },
  Profile: {
    Main: "Profile.",
    EmailLabel: "Profile.EmailLabel",
    EmailRequired: "Profile.EmailRequired",
    EmailUsed: "Profile.EmailUsed",
    FinishButton: "Profile.FinishButton",
    IsEmail: "Profile.IsEmail",
    LangRequired: "Profile.LangRequired",
    LanguagePreferenceLabel: "Profile.LanguagePreferenceLabel",
    Legend: "Profile.Legend",
    PhoneLabel: "Profile.PhoneLabel",
    PostalCodeLabel: "Profile.PostalCodeLabel",
    PostalCodeRequired: "Profile.PostalCodeRequired",
    ProfileInstructions: "Profile.ProfileInstructions",
    ProfileTitle: "Profile.ProfileTitle",
    Success: "Profile.Success",
    UserNameLabel: "Profile.UserNameLabel",
    UserNameRequired: "Profile.UserNameRequired",
    ValidPhone: "Profile.ValidPhone",
  },
  Register: {
    Main: "Register.",
    ConfirmPasswordLabel: "Register.ConfirmPasswordLabel",
    ConfirmPasswordRequired: "Register.ConfirmPasswordRequired",
    EmailInUse: "Register.EmailInUse",
    EmailLabel: "Register.EmailLabel",
    EmailRequired: "Register.EmailRequired",
    FinishButton: "Register.FinishButton",
    IsEmail: "Register.IsEmail",
    LangRequired: "Register.LangRequired",
    LanguagePreferenceLabel: "Register.LanguagePreferenceLabel",
    PageInstructions1: "Register.PageInstructions1",
    PageInstructions2: {
      Main: "Register.PageInstructions2.",
      Part1: "Register.PageInstructions2.Part1",
      Part2: "Register.PageInstructions2.Part2",
    },
    PageInstructions3: "Register.PageInstructions3",
    PasswordCompare: "Register.PasswordCompare",
    PasswordLabel: "Register.PasswordLabel",
    PasswordRequired: "Register.PasswordRequired",
    PhoneLabel: "Register.PhoneLabel",
    PostalCodeLabel: "Register.PostalCodeLabel",
    PreviousButton: "Register.PreviousButton",
    RegisterStep1Instructions: "Register.RegisterStep1Instructions",
    StartNextButton: "Register.StartNextButton",
    Step0Legend: "Register.Step0Legend",
    Step1Legend: "Register.Step1Legend",
    Title: "Register.Title",
    UserNameLabel: "Register.UserNameLabel",
    UserNameRequired: "Register.UserNameRequired",
    ValidPhone: "Register.ValidPhone",
    ValidPostal: "Register.ValidPostal",
  },
  RenewPost: {
    Main: "RenewPost.",
    Failure: "RenewPost.Failure",
    Success: "RenewPost.Success",
  },
  Search: {
    Main: "Search.",
    FinishButton: "Search.FinishButton",
    Legend: "Search.Legend",
    SearchCategoryPickerLabel: "Search.SearchCategoryPickerLabel",
    SearchCategoryPickerLabel1: "Search.SearchCategoryPickerLabel1",
    SearchErrorMessage: "Search.SearchErrorMessage",
    SearchInstructions: "Search.SearchInstructions",
    SearchPageTitle: "Search.SearchPageTitle",
    SearchResults: "Search.SearchResults",
    SearchTermLabel: "Search.SearchTermLabel",
  },
  Splash: {
    Main: "Splash.",
    Instructions: "Splash.Instructions",
    Welcome: "Splash.Welcome",
  },
  TestMain: {
    Main: "TestMain",
    Instructions: "TestMain.Instructions",
  },
  ViewPost: {
    Main: "ViewPost.",
    vpUserContact: "ViewPost.vpUserContact",
    vpUserEdit: "ViewPost.vpUserEdit",
    vpUserItems: "ViewPost.vpUserItems",
    vpUserPhone: "ViewPost.vpUserPhone",
  },
});

export default pagesWithLabels;
