# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/api" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/bff" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/idp" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"

  # now update all the docker files

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/bff"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/db"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/idp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/proxy"
    schedule:
      interval: "weekly"
