version: "3.3"

services:
    app:
        image: node:latest
        environment:
            - CHOKIDAR_USEPOLLING=1
            - HTTPS=true
            - PORT=3000
            - SSL_CERT_FILE=/ssl/cert.pem
            - SSL_KEY_FILE=/ssl/key.pem
        volumes:
            - ./app/cra:/app
            - ./app/docker-prep.dev.sh:/tmp/docker-prep.dev.sh
            - ./ssl:/ssl
            # - ./app/proxy/conf:/etc/nginx/conf.d
        entrypoint: /bin/bash -x /tmp/docker-prep.dev.sh
        ports:
            - 3000:3000
        networks:
            - nsw
        depends_on:
            - api
            - bff
            - idp
            - db
    bff:
        image: mcr.microsoft.com/dotnet/sdk:7.0
        working_dir: /app
        volumes:
            - .:/app
            - ${HOME}/.nuget:${HOME}/.nuget
            - ./ssl:/ssl            
            # - ${HOME}/.dotnet/dotnet:/usr/bin/dotnet
            # - /usr/share/dotnet:/usr/share/dotnet
        environment:
            - HOME:/home/${USER}
        entrypoint: /app/bff/src/entrypoint.sh
        ports:
            - 5004:5004
            - 5005:5005
        networks:
            - nsw
        depends_on:
            - api
            - idp
    idp:
        image: mcr.microsoft.com/dotnet/sdk:7.0
        working_dir: /app
        volumes:
            - .:/app
            - ${HOME}/.nuget:${HOME}/.nuget            
            - ./ssl:/ssl
            # - ${HOME}/.dotnet/dotnet:/usr/bin/dotnet
            # - /usr/share/dotnet:/usr/share/dotnet
        environment:
            - HOME:/home/${USER}
            - DOTNET_NSW_Development:"Server=db;Database=IdSrvConfig;User Id=nsw_idsrv;Password='testPa55w0rd!';"
        entrypoint: /app/idp/src/entrypoint.sh
        ports:
            - 5006:5006
            - 5007:5007 
        networks:
            - nsw
        depends_on:
            - db
            - api
    api:
        image: mcr.microsoft.com/dotnet/sdk:7.0
        working_dir: /app
        volumes:
            - ./api/src:/app
            - ./ssl:/ssl            
            - ${HOME}/.nuget:${HOME}/.nuget  
            # - ${HOME}/.dotnet/dotnet:/usr/bin/dotnet
            # - /usr/share/dotnet:/usr/share/dotnet
        environment:
            - HOME:/home/${USER}
            - DOTNET_NSW_Development:"Server=db;Database=nswData;User Id=nsw_data;Password='testPa55w0rd!';"                          
        entrypoint: /app/entrypoint.sh
        ports:
            - 5002:5002
            - 5003:5003
        networks:
            - nsw
        depends_on:
            - db
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - MSSQL_SA_PASSWORD=s00p3rS3cvr#
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
        volumes:
            - ./db/data:/var/opt/mssql/data
            - ./db/entrypoint.sh:/tmp/entrypoint.sh
            - ./db/create_idpConfigDb.sql:/tmp/create_idpConfigDb.sql
            - ./db/create_nswDataDb.sql:/tmp/create_nswDataDb.sql
            - ./db/configure-db.sh:/tmp/configure-db.sh
        entrypoint: /tmp/entrypoint.sh
        networks:
            - nsw
        ports:
            - 1533:1433
            - 1534:1434            
    proxy:
        image: nginx:latest
        volumes:
            - ./proxy/conf:/etc/nginx/conf.d
            - ./ssl:/ssl
        depends_on:
            - app
            - idp
            - bff
            - api
        networks:
            - nsw
        ports:
            - 80:80
            - 443:443

networks:
    nsw: