FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env

COPY ./ssl/bff.* /ssl/

# set the application folder on the service
WORKDIR /app
# copy the aspnetcore debugger from the web

# restore the project's nuget packages
COPY . .
RUN dotnet restore ./bff/src/NSW_BFF.csproj
# build the application
RUN dotnet build -c Debug -o out ./bff/src/NSW_BFF.csproj

# expose the ports
EXPOSE 5004 5005

# run the project
ENTRYPOINT  ["dotnet", "run", "--project", "/app/bff/src/NSW_BFF.csproj"]
