FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env

# set the application folder on the service
WORKDIR /app
# copy the aspnetcore debugger from the web

# restore the project's nuget packages
COPY ./src/*.csproj ./
RUN dotnet restore

# build the application
RUN dotnet build -c Debug -o out

# expose the ports
EXPOSE 5006 5007

# run the project
ENTRYPOINT  ["dotnet", "watch", "run", "IDP.dll"]
