FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-env

# set the application folder on the service
WORKDIR /app
# copy the aspnetcore debugger from the web

# restore the project's nuget packages
COPY . .
RUN dotnet restore ./src/API.csproj
# build the application
RUN dotnet build -c Debug -o out ./src/API.csproj

# expose the ports
EXPOSE 5002 5003
# run the project
ENTRYPOINT  ["dotnet", "watch", "run", "API.dll"]
